### ISSUE TITLE
Image anntoation MVP

### ISSUE THREAD

**Issue by RFSH** [informatics-isi-edu/openseadragon-viewer#36]
Must have,
- [x] Deterministic output SVG (style vs. attribute, etc.) (#39)
- [x] Add default color to annotations that don't have any color (when the input SVG doesn't have any color).
- [x] Handle thickness in multiple zoom levels
  - Test on non-CZI images
  - Add URL parameter to turn this on/off (opposite of what the heuristics are going to be)
- [x] Proper URL parameter handling
  - make sure they are following the same naming convention
  - update documentation
- [x] Screenshot issue (#35)
- [x] Scalibiltiy improvements in Chaise.
- [x] Add color block to anatomy term corresponding to color used in annotation (#41)
- [x] Logging support in Chaise.

Good to have,
- [ ] Edit discard bug (undo) (#42)
- [ ] Improve SVG performance in osd viewer.
- [ ] Make the annotation lines easier to click (#34)
- [ ] Disable the osd toolbar in non-draw mode (instead of hiding it.)
- [ ] Channel vs. Scene (#25)
- [ ] Error handling (bare minimum)

**Comment by RFSH** [comment]
I'm going to close this epic as the original "Must have" list is done.
