### ISSUE TITLE
Multi-Z support

### ISSUE THREAD

**Issue by RFSH** [informatics-isi-edu/openseadragon-viewer#57]
Currently, the OSD viewer shows all the given images together. There's no concept of different collections (or galleries) involved. This is simply because all the currently displayed images are showing one single z-index. As the next step, we need to expand on this. Users should be able

- See the list of available z-index
- Change from one z-index to another. And then the displayed channels should change accordingly. 

The following are the list of tasks that I could think of (subject to change):

- [x] (Bhavya) Investigate how we can switch from a list of images to the other in OSD. Whether there's an API for it in OSD or we have to manually remove the old images and then add the new images. 
- [x] (Bhavya) Draft a UI for how the z-index control would look like.
  - what's the layout?
  - what are the available controls?
  - where should the image gallery go?
- [x] (Bhavya) Finalize the UI (#60)
- [x] (Aref) (#61) Draft how OSD viewer and Chaise should communicate. How OSD should get the list, and then choose a z-index from the list and send it to Chaise.
  - where the get the thumbnails
  - how to match z-index to thumbnail
  - how to fetch all the z-indices
  - pagination

- [x] Update regression tests and make sure they are working properly.

**Comment by rastogi-bhavya** [comment]
For the first part, where we want to switch between a list of images, I found this discussion on github https://github.com/openseadragon/openseadragon/issues/1250 .
The solution to the problem in the above github post has been solved here: https://codepen.io/iangilman/pen/PjdyGv 
I think this is what we are looking for in terms of changing the image in OSD.

**Comment by rastogi-bhavya** [comment]
Assumption: multi-z is a feature that is not very common, therefore the UI does not need to be always present

For UI I was thinking something similar to `Channel`, i.e. have a button called `Show multi-z` (or something like this). When the user clicks on this button, an translucent row (similar to when show channel is clicked) will be shown which will have the following functionalities
- Preview of all z axis's
- Current z axis (eg 4 of 25)
- button (eg. right and left arrow) to move to next or previous axis
- a scroll bar, for scrolling through all the previews
- clicking on a preview would select that axis
- an input field to jump to a particular field

**Comment by carlkesselman** [comment]
It might be a good idea to do a quick wireframe… powerpoint slide, or even a hand sketch to make sure we are all in agreement here…..

Carl

----------------------------------------------------------

Dr. Carl Kesselman
Dean’s Professor, Epstein Department of Industrial and Systems Engineering
Fellow, Information Sciences Institute Viterbi School of Engineering Professor,

Preventive Medicine Keck School of Medicine

University of Southern California
4676 Admiralty Way, Suite 1001, Marina del Rey, CA  90292-6695
Phone:  +1 (310) 448-9338
 Email:  carl@isi.edu
Web: http://www.isi.edu/~carl
On Dec 1, 2020, 4:53 PM -0800, Bhavya Rastogi <notifications@github.com>, wrote:

Assumption: multi-z is a feature that is not very common, therefore the UI does not need to be always present

For UI I was thinking something similar to Channel, i.e. have a button called Show multi-z (or something like this). When the user clicks on this button, an translucent row (similar to when show channel is clicked) will be shown which will have the following functionalities

  *   Preview of all z axis's
  *   Current z axis (eg 4 of 25)
  *   button (eg. right and left arrow) to move to next or previous axis
  *   a scroll bar, for scrolling through all the previews
  *   clicking on a preview would select that axis
  *   an input field to jump to a particular field
