### ISSUE TITLE
Multi-z support improvements

### ISSUE THREAD

**Issue by RFSH** [informatics-isi-edu/openseadragon-viewer#66]
_This issue might be updated later based on the feedback that we receive._

**UI Improvements / bugs**:
- [ ] There should be a minimum width for the z-plane list (based on minimum number of displayed thumbnails.) if the available width is less than that, we should just give up and show a horizontal scrollbar.
- [ ] Show a better loader. We could show the thumbnails like [this](https://codepen.io/brucevang/pen/qZOPwR) (how facebook does it) while the page is loading.
- [ ] Find a way to reduce the visible shift on load.

**Comment by RFSH** [comment]
A bigger epic was created. So I'm going to close this.
